=== TrafficPLANit/PLANitIO/src/test/resources/input/macroscopicsupplyinput.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:gml="http://www.opengis.net/gml">
<xs:import namespace="http://www.opengis.net/gml" schemaLocation="http://schemas.opengis.net/gml/3.1.1/base/gml.xsd" />

	<!-- simple types -->
	<xs:simpleType name="direction">
		<xs:annotation>
			<xs:documentation>
				Choice between direction from a->b, or b->a
			</xs:documentation>
		</xs:annotation>	
		<xs:restriction base="xs:string">
			<xs:enumeration value="a_b"/>
      		<xs:enumeration value="b_a"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:attribute name="srsname" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Global definition of the spatial reference system used for all gml elements. Should comply with the srs naming conventions of such a string
			</xs:documentation>
		</xs:annotation>
	</xs:attribute>

	<!-- simple elements -->
	<xs:element name="name" type="xs:string"/>

	<xs:element name="maxdensitylane" type="xs:float" default="180.0">
		<xs:annotation>
			<xs:documentation>
				Maximum density of a lane in veh/km/lane, default set to 180
			</xs:documentation>
		</xs:annotation>	
	</xs:element>
	
	<xs:element name="capacitylane" type="xs:float" default="1800.0">
		<xs:annotation>
			<xs:documentation>
				Maximum capacity, i.e., throughput, of a lane in veh/km/lane, default set to 1800
			</xs:documentation>
		</xs:annotation>	
	</xs:element>
		
	<xs:element name="maxspeed" type="xs:float">
		<xs:annotation>
			<xs:documentation>
				Maximum speed in km/h
			</xs:documentation>
		</xs:annotation>	
	</xs:element>
		
	<xs:element name="critspeed" type="xs:float">
		<xs:annotation>
			<xs:documentation>
				Speed at capacity, i.e., critical speed of a lane in km/h
			</xs:documentation>
		</xs:annotation>	
	</xs:element>
		
	<xs:element name="noflanes" type="xs:positiveInteger" default="1">
		<xs:annotation>
			<xs:documentation>
				Number of lanes of a link segment
			</xs:documentation>
		</xs:annotation>	
	</xs:element>
	
	<xs:element name="length" type="xs:float">
		<xs:annotation>
			<xs:documentation>
				Length of a link in km which overrides the actual length which is normally deduced from the geo spatial information 
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<!-- Complex elements -->
	<xs:element name="configuration">
		<xs:annotation>
			<xs:documentation>
				Configuration, i.e., meta data of the network infrastructure 
			</xs:documentation>
		</xs:annotation>	
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element ref="linksegmenttypes" minOccurs="0">
					<xs:annotation>
						<xs:documentation>
							Link segment types define the different types of link segment properties that can be attributed to links. Note
							that it is allowed to not define this element. In that case all link(segments) are assumed to be of the same default
							link segment type. 
						</xs:documentation>
					</xs:annotation>	  	
				</xs:element>			
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
	<xs:element name="infrastructure">
		<xs:annotation>
			<xs:documentation>
				The physical infrastructure consists of nodes and links 
			</xs:documentation>
		</xs:annotation>		
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element ref="nodes"/>
  				<xs:element ref="links"/>
  			</xs:sequence>
  		<xs:attribute ref="srsname" use="xs:optional">
  			<xs:annotation>
				<xs:documentation>
					Spatial reference system chosen for infrastructure, if absent Cartesian system is assume with 0,0 to be the top left 
				</xs:documentation>
			</xs:annotation>
  		</xs:attribute>
  		</xs:complexType>
  	</xs:element>  	
  	
	<xs:element name="linksegmenttypes">
		<xs:annotation>
			<xs:documentation>
				The link segment types can be used to group similar link characteristics in one place. Each link segment has exactly one 
				link segment type associated with it
			</xs:documentation>
		</xs:annotation>		
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element name="linksegmenttype" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="name"/>
							<xs:element ref="maxdensitylane" minOccurs="0">
								<xs:annotation>
									<xs:documentation>
										When not present, the default maximum density per lane will be applied
									</xs:documentation>
								</xs:annotation>	
							</xs:element>
							<xs:element ref="capacitylane" minOccurs="0">
								<xs:annotation>
									<xs:documentation>
										When not present, the default capacity per lane will be applied
									</xs:documentation>
								</xs:annotation>							
							</xs:element>
							<xs:element name="mode">
								<xs:annotation>
									<xs:documentation>
										Mode specific attributes associated with the link segment type are the maximum and critical speed.
										If a mode is not defined on the link segment type it is assumed the mode is not allowed on the link segment.
									</xs:documentation>
								</xs:annotation>							
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="maxspeed"/>
										<xs:element ref="critspeed"/>
									</xs:sequence>
									<xs:attribute name="ref" type="xs:positiveInteger">
										<xs:annotation>
											<xs:documentation>
												Refers to the unique identifier for the mode this information relates to. If '0' is used
												all non-defined modes on the link segment type will take on the values provided for this 'all modes' entry.
											</xs:documentation>
										</xs:annotation>									
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger"/>
					</xs:complexType>
				</xs:element>  				
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>  	
  	
	<xs:element name="linksegment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="noflanes"/>		
				<xs:element ref="maxspeed"/>
			</xs:sequence>
			<xs:attribute name="id" 		type="xs:positiveInteger" 	use="required"/>
			<xs:attribute name="dir" 		type="direction"			use="required"/>
			<xs:attribute name="nodearef" 	type="xs:positiveInteger" 	use="required">
				<xs:annotation>
					<xs:documentation>
						Refers to the unique node identifier (id) associated with node 'a' of this link segment
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="nodebref" 	type="xs:positiveInteger" 	use="required">
				<xs:annotation>
					<xs:documentation>
						Refers to the unique node identifier associated with node 'b' of this link segment
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>			
			<xs:attribute name="typeref" 	type="xs:positiveInteger" 	use="optional">
				<xs:annotation>
					<xs:documentation>
						Refers to the unique identifier (id) associated with link segment type of this link segment.
						Note that while typeref is optional, this is only allowed when no link segment types have been defined 
						and we can assume it safe to revert to the single default link segment type that has been created internally.						
					</xs:documentation>
				</xs:annotation>			
			</xs:attribute>			
		</xs:complexType>
	</xs:element>  		  	

	<xs:element name="links">
		<xs:annotation>
			<xs:documentation>
				The connections between a pair of nodes						
			</xs:documentation>
		</xs:annotation>	
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element name="link" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>
							The connection between a pair of nodes which has no transport related information yet. This is purely the graph						
							based definition of the structure of some network
						</xs:documentation>
					</xs:annotation>	  				
  					<xs:complexType>
  						<xs:sequence>
  							<xs:element ref="name"/>
  							<!-- a link segment has a direction, at most two directions exist per link -->
  							<xs:element ref="linksegment" minOccurs="1" maxOccurs="2">
								<xs:annotation>
									<xs:documentation>
										Each link segment has a direction and at most two directions exist per link
									</xs:documentation>
								</xs:annotation>	  				  							
  							</xs:element>
  							<xs:element ref="gml:LineString" minOccurs="0">
								<xs:annotation>
									<xs:documentation>
										Each link segment has an optional gml LineString to define shape points. Note that one can choose to 
										either duplicate the node points or not here
									</xs:documentation>
								</xs:annotation>	  				  							
  							</xs:element>  							
  							<xs:element ref="length" minOccurs="0">
								<xs:annotation>
									<xs:documentation>
										Optional length property which overrides any geo spatial length which is deduced from the coordinate system
									</xs:documentation>
								</xs:annotation>	  							
  							</xs:element> 							
  						</xs:sequence>
  						<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  					</xs:complexType>		
  				</xs:element>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>   	
	
	<!-- Root element -->
	<xs:element name="macroscopicnetwork">
		<xs:annotation>
			<xs:documentation>
				Root element of the macroscopic network infrastructure. Defines the physical road network and its properties
			</xs:documentation>
		</xs:annotation>	
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element ref="configuration" minOccurs="0">
					<xs:annotation>
						<xs:documentation>
							When configuration is absent we assume a single link segment type for the entire simulation and a simple Cartesian coordinate system with top-left (0,0) 
						</xs:documentation>
					</xs:annotation>  				
  				</xs:element>
  				<xs:element ref="infrastructure"/>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
	<xs:element name="nodes">
		<xs:annotation>
			<xs:documentation>
				Nodes represent the locations where links (roads) intersect and traffic interacts with each other. 
			</xs:documentation>
		</xs:annotation>  					
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element name="node" maxOccurs="unbounded">
  					<xs:complexType>
  						<xs:sequence>
  							<xs:element ref="name"/>
  							<xs:element ref="gml:Point">
  								<xs:annotation>
									<xs:documentation>
										Each node should have a location via a gml:Point definition based on the gml xsd schema
									</xs:documentation>
								</xs:annotation> 
  							</xs:element>
  						</xs:sequence>
  						<xs:attribute name="id" type="xs:positiveInteger"/>
  					</xs:complexType>		
  				</xs:element>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>  	  	  	
</xs:schema>

=== TrafficPLANit/PLANitIO/src/test/resources/input/ExpandedExample/macropscopicsupplyinput.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<macroscopicnetwork
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xmlns:gml="http://www.opengis.net/gml"											
	 xsi:noNamespaceSchemaLocation="../schema/macroscopicsupplyinput.xsd">						<!-- use xs:import to import the gml namespace into the xsd to specify the reused elements -->
	<configuration>																		<!-- optional, single linksegmenttype assumed when absent -->
		<linksegmenttypes>																<!-- optional, if not present a default link segment type is used for all links -->
			<linksegmenttype id="1">													<!-- mandatory attribute -->
				<name>local road</name>													<!-- optional -->
				<maxdensitylane>180</maxdensitylane>									<!-- optional, has default -->
				<capacitylane>2000</capacitylane>										<!-- optional, has default -->
				<mode ref="1">															<!-- optional, when 0 it refers to all modes, when a mode is absent the mode is assumed to be banned from the link segment -->
					<maxspeed>40</maxspeed>												<!-- mandatory, should be lower or equal than link max speed when present -->
					<critspeed>35</critspeed>											<!-- optional (no default), idfdefined should be lower or equal than (mode specific) link max speed when present, represents the speed at capacity -->
				</mode>
			</linksegmenttype>
		</linksegmenttypes>			
	</configuration>
	<infrastructure srsname="EPSG:4326">												<!-- srsName indicates the spatial reference system used for all gml elements, if not provided a cartesian (top-left: 0,0) system is assumed -->  
		<nodes>
			<node id="1"> 																<!-- mandatory attribute -->
				<name>George Street roundabout</name> 									<!-- optional -->
                <gml:Point> 															<!-- mandatory -->
                    <gml:pos>150.512796 -34.900145</gml:pos>
                </gml:Point>														
			</node>
			<node id="2"> 
				<name>Broadway intersection</name>
				<gml:Point> 															<!-- mandatory -->
                    <gml:pos>150.512527 -34.900319</gml:pos>
                </gml:Point> 					
			</node>				
		</nodes>		
		<links>
			<link id="1">																<!-- optional since it can be derived from the two nodes -->
				<name>Broadway</name>													<!-- optional -->
				<linksegment id="1" dir="a_b" nodearef="1" nodebref="2" typeref="1">	<!-- mandatory attributes, except for id can be derived from direction, and typeref which if absent must mean there are no linksegmenttypes defined and we use default one-->
					<noflanes>2</noflanes>												<!-- optional, has default -->
					<maxspeed>50</maxspeed>												<!-- optional, has (deduced?) default (Q:do we make this part of link segmenttype or not?)-->						
				</linksegment>
				<linksegment id="2" dir="b_a" nodearef="1" nodebref="2" typeref="1">
					<noflanes>1</noflanes>
					<maxspeed>50</maxspeed>
				</linksegment>					
				<gml:LineString>														<!-- optional, indicating shape points on the link, in case the first and last coordinate do not match the node points, the node points are added to the string -->
					<gml:coordinates cs=" " ts=",">100,200 150,300</gml:coordinates>
				</gml:LineString>	
				<length>1.33</length>													<!-- manual override of link length in case for some reason the coordinates should not be used to deduce the length -->				
			</link>
		</links>
	</infrastructure>
</macroscopicnetwork>
