=== TrafficPLANit/PLANitIO/src/test/resources/input/macroscopicdemandinput.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- simple elements -->
	<xs:element name="name" type="xs:string"/>
	<xs:element name="pcu" type="xs:float" default="1"/>
	<xs:element name="starttime" type="xs:time" default="00:00:00"/> <!-- hh:mm:ss -->
	<xs:element name="duration">
		<xs:simpleType>
			<!-- restricted by maximum number of seconds in a day -->
	    	<xs:restriction base="xs:positiveInteger">
      			<xs:minInclusive value="1"/>
      			<xs:maxInclusive value="86400"/> 
	    	</xs:restriction>
		</xs:simpleType>
	</xs:element>    
	
	<!-- Root element -->
	<xs:element name="macroscopicdemand">
  		<xs:complexType>
  			<xs:sequence>
  				<!-- when configuration is absent it must have been part of another demand input file that has already been parsed -->
  				<xs:element ref="configuration" minOccurs="0"/>
  				<xs:element ref="oddemands"/>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
  	<!-- Configuration of the demand, i.e., the metadata -->
	<xs:element name="configuration">
  		<xs:complexType>
  			<xs:sequence>
  				<!-- when absent, single mode with pcu=1 is assumed and no references to modes are possible in subsequent elements -->
  				<xs:element ref="modes" minOccurs="0"/>
  				<!-- when absent, single traveller type is assumed and no references to traveller types are possible in subsequent elements -->
  				<xs:element ref="travellertypes" minOccurs="0"/>
  				<xs:element ref="userclasses" />
  				<xs:element ref="timeperiods"/>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
	<xs:element name="oddemands">
  		<xs:complexType>
  			<xs:choice maxOccurs="unbounded">
      			<xs:element ref="odmatrix"/>
      			<xs:element ref="odrowmatrix"/>
      			<xs:element ref="odrawmatrix"/>
    		</xs:choice>
  		</xs:complexType>
  	</xs:element>  	
  	
  	<!-- full (element-by-element) or sparse matrix definition -->
	<xs:element name="odmatrix">
  		<xs:complexType>
  			<xs:sequence maxOccurs="unbounded">
  				<!-- origin row in od matrix -->
      			<xs:element name="o">
      				<xs:complexType>
      					<xs:sequence>
      						<!-- destination cell in origin row matrix -->
      						<xs:element name="d" maxOccurs="unbounded">
								<xs:complexType>	      						
									<xs:simpleContent>
										<xs:extension base="xs:string">
					      					<!-- absence only allowed when all destination (zones) are provided, i.e., number of entries equates to number of zones -->
					      					<xs:attribute name="ref" type="xs:positiveInteger" use="optional"/>
					      				</xs:extension>      					
				      				</xs:simpleContent>      						
				      			</xs:complexType>
      						</xs:element>
      					</xs:sequence>
	      				<!-- absence only allowed when all origins (zones) are provided, i.e., number of rows equates to number of zones -->
	      				<xs:attribute name="ref" type="xs:positiveInteger" use="optional"/>      					
      				</xs:complexType>
      			</xs:element>
    		</xs:sequence>		
			<xs:attribute name="timeperiodref" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="userclassref" type="xs:positiveInteger" use="required"/>
  		</xs:complexType>  		
  	</xs:element> 
  	
  	<xs:element name="odrawmatrix">
  		<xs:complexType>
  			<xs:sequence>
  				<!-- csv like string of entire matrix (including zero values) formatted based on os (origin separator) and ds (destination separator) attribute configuration -->
      			<xs:element name="values">
					<xs:complexType>      			
	      				<xs:simpleContent>
	      					<xs:extension base = "xs:string">
		      					<!-- absence only allowed when all origins (zones) are provided, i.e., number of rows equates to number of zones -->
		      					<xs:attribute name="os" type="xs:string" use="optional" default=" "/>
								<xs:attribute name="ds" type="xs:string" use="optional" default=","/>
							</xs:extension>	      				      					
	      				</xs:simpleContent>
					</xs:complexType>	      				
      			</xs:element>
    		</xs:sequence>		
			<xs:attribute name="timeperiodref" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="userclassref" type="xs:positiveInteger" use="required"/>
  		</xs:complexType>  		
  	</xs:element> 
  	
	<xs:element name="odrowmatrix">
  		<xs:complexType>
  			<xs:sequence maxOccurs="unbounded">
  				<!-- origin row in od matrix -->
      			<xs:element name="odrow">
					<xs:complexType>      			
	      				<xs:simpleContent>
	      					<xs:extension base="xs:string">
	      						<!-- reference to origin row,, gaps in the numbering indicate zero content rows, absence of ref only allowed if all rows are ordered and available for all zones  -->
								<xs:attribute name="ref" type="xs:positiveInteger" use="optional"/>
							</xs:extension>	      				      					
	      				</xs:simpleContent>
					</xs:complexType>	      				
      			</xs:element>
    		</xs:sequence>		
			<xs:attribute name="timeperiodref" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="userclassref" type="xs:positiveInteger" use="required"/>
			<!-- destination separator used for each row -->
			<xs:attribute name="ds" type="xs:string" use="optional" default=","/>			
  		</xs:complexType>  		
  	</xs:element>  	
  	
	<xs:element name="modes">
  		<xs:complexType>
  			<xs:sequence>
			  	 <xs:element name="mode" maxOccurs="unbounded">
			  		<xs:complexType>
			  			<xs:sequence>
			  				<xs:element ref="name" minOccurs="0"/>
			  				<xs:element ref="pcu" minOccurs="0"/>
			  			</xs:sequence>
			  			<xs:attribute name="id" type="xs:positiveInteger" use="required"/>  			
			  		</xs:complexType>
			  	</xs:element>  			
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
	<xs:element name="timeperiods">
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element name="timeperiod" maxOccurs="unbounded">
  					<xs:complexType>
			  			<xs:sequence>
			  				<xs:element ref="name"/>
			  				<xs:element ref="starttime" minOccurs="0"/>
			  				<xs:element ref="duration"/>
			  			</xs:sequence>  					
						<xs:attribute name="id" type="xs:positiveInteger" use="required"/>	   					
  					</xs:complexType>
  				</xs:element>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>   	
  	  	
	<xs:element name="travellertypes">
  		<xs:complexType>
  			<xs:sequence>
			  	<xs:element name="travellertype" maxOccurs="unbounded">
			  		<xs:complexType>
			  			<xs:sequence>
			  				<xs:element ref="name"/>
			  			</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" use="required"/>	  			
			  		</xs:complexType> 		
			  	</xs:element>    			
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>  	
  	  	
	<xs:element name="userclasses">
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element name="userclass" maxOccurs="unbounded">
  					<xs:complexType>
			  			<xs:sequence>
			  				<xs:element ref="name"/>
			  			</xs:sequence>  					
						<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
						<xs:attribute name="moderef" type="xs:positiveInteger" use="optional"/>
						<xs:attribute name="travellertyperef" type="xs:positiveInteger" use="optional"/>	   					
  					</xs:complexType>
  				</xs:element>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>  	  	
  	
</xs:schema>

=== TrafficPLANit/PLANitIO/src/test/resources/route_choice/xml/test4raw2/demands.xml
<?xml version="1.0" encoding="UTF-8"?>
<macroscopicdemand xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                                     xsi:noNamespaceSchemaLocation="../../../../../main/resources/macroscopicdemandinput.xsd">
      
   <demandconfiguration>
	    <userclasses>
	    	<userclass id="1" moderef="1">
	    		<name>1</name>
	    	</userclass>
	    </userclasses>
	    <timeperiods>
	    	<timeperiod id="0">
	    		<name>1</name>
	    		<starttime>00:00:01</starttime>
	    		<duration>86400</duration>
	    	</timeperiod>
	    </timeperiods> 
   </demandconfiguration>
       
	<oddemands>
		<odrawmatrix timeperiodref="0" userclassref="1">
			<values os=" " ds="+">100+200+300+400 200+400+600+800 300+600+900+1200 400+800+1200+1600</values>
		</odrawmatrix>
	</oddemands>
</macroscopicdemand>

=== TrafficPLANit/PLANitIO/src/test/resources/route_choice/xml/test1/demands.xml
<?xml version="1.0" encoding="UTF-8"?>
<macroscopicdemand xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                                     xsi:noNamespaceSchemaLocation="../../../../../main/resources/macroscopicdemandinput.xsd">
      
   <configuration>
	    <userclasses>
	    	<userclass id="1" moderef="1">
	    		<name>1</name>
	    	</userclass>
	    </userclasses>
	    <timeperiods>
	    	<timeperiod id="0">
	    		<name>1</name>
	    		<starttime>00:00:01</starttime>
	    		<duration>86400</duration>
	    	</timeperiod>
	    </timeperiods> 
   </configuration>
       
	<oddemands>
		<odcellbycellmatrix timeperiodref="0" userclassref="1">
			<o ref="3">																
				<d ref="4">1000</d> 
			</o>
			<o ref="5">																
				<d ref="1">1000</d> 
			</o>
			<o ref="2">																
				<d ref="6">1000</d> 
			</o>
		</odcellbycellmatrix>
	</oddemands>
</macroscopicdemand>

=== TrafficPLANit/PLANitIO/src/test/resources/route_choice/xml/test5/demands.xml
<?xml version="1.0" encoding="UTF-8"?>
<macroscopicdemand xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                        xsi:noNamespaceSchemaLocation="../../../../../main/resources/schema/macroscopicdemandinput.xsd">
      
   <configuration>
	    <userclasses>
	    	<userclass id="1" moderef="1">
	    		<name>1</name>
	    	</userclass>
	    	<userclass id="2" moderef="2">
	    		<name>2</name>
	    	</userclass>
	    </userclasses>
	    <timeperiods>
	    	<timeperiod id="1">
	    		<name>1</name>
	    		<starttime>00:00:01</starttime>
	    		<duration>86400</duration>
	    	</timeperiod>
	    </timeperiods> 
   </configuration>
       
	<oddemands>
		<odmatrix timeperiodref="1" userclassref="1">
			<o ref="31">																
				<d ref="27">3000</d> 
			</o>
		</odmatrix>
		<odmatrix timeperiodref="1" userclassref="2">
			<o ref="31">																
				<d ref="27">600</d> 
			</o>
		</odmatrix>
	</oddemands>
</macroscopicdemand>

=== TrafficPLANit/PLANitIO/src/test/resources/basic/xml/test13/demands.xml
<?xml version="1.0" encoding="UTF-8"?>
<macroscopicdemand xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                        xsi:noNamespaceSchemaLocation="../../../../../main/resources/macroscopicdemandinput.xsd">
      
   <demandconfiguration>
	    <userclasses>
	    	<userclass id="1" moderef="1">
	    		<name>1</name>
	    	</userclass>
	    </userclasses>
	    <timeperiods>
	    	<timeperiod id="0">
	    		<name>Time Period 1</name>
	    		<starttime>00:00:01</starttime>
	    		<duration>28800</duration>
	    	</timeperiod>
	    	<timeperiod id="1">
	    		<name>Time Period 2</name>
	    		<starttime>08:00:01</starttime>
	    		<duration>28800</duration>
	    	</timeperiod>
	    	<timeperiod id="2">
	    		<name>Time Period 3</name>
	    		<starttime>16:00:01</starttime>
	    		<duration>28800</duration>
	    	</timeperiod>
	    </timeperiods> 
   </demandconfiguration>
       
	<oddemands>
		<odcellbycellmatrix timeperiodref="0" userclassref="1">
			<o ref="1">																
				<d ref="2">1</d> 
			</o>
		</odcellbycellmatrix>
		<odcellbycellmatrix timeperiodref="1" userclassref="1">
			<o ref="1">																
				<d ref="3">1</d> 
			</o>
		</odcellbycellmatrix>
		<odcellbycellmatrix timeperiodref="2" userclassref="1">
			<o ref="1">																
				<d ref="4">1</d> 
			</o>
		</odcellbycellmatrix>
	</oddemands>
</macroscopicdemand>

=== TrafficPLANit/PLANitIO/src/test/resources/route_choice/xml/test4/demands.xml
<?xml version="1.0" encoding="UTF-8"?>
<macroscopicdemand xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                                     xsi:noNamespaceSchemaLocation="../../../../../main/resources/macroscopicdemandinput.xsd">
      
   <demandconfiguration>
	    <userclasses>
	    	<userclass id="1" moderef="1">
	    		<name>1</name>
	    	</userclass>
	    </userclasses>
	    <timeperiods>
	    	<timeperiod id="0">
	    		<name>Time Period 1</name>
	    		<starttime>00:00:01</starttime>
	    		<duration>86400</duration>
	    	</timeperiod>
	    </timeperiods> 
   </demandconfiguration>
       
	<oddemands>
		<odrowmatrix timeperiodref="0" userclassref="1">
			<odrow ref="1">100,200,300,400</odrow>
			<odrow ref="2">200,400,600,800</odrow>
			<odrow ref="3">300,600,900,1200</odrow>
			<odrow ref="4">400,800,1200,1600</odrow>
		</odrowmatrix>
	</oddemands>
</macroscopicdemand>

=== TrafficPLANit/PLANitIO/src/test/resources/input/ExpandedExample/macroscopicdemandinput.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<macroscopicdemand
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"								
	 xsi:noNamespaceSchemaLocation="../schema/macroscopicdemandinput.xsd">					<!-- use xs:import to import the gml namespace into the xsd to specify the reused elements -->
	<configuration>																	<!-- optional -> if not present we assume it aligns with earlier demand inputs on the project -->	
		<travellertypes>															<!-- optional, if not present, single default traveller type assumed -->
			<travellertype id="1">
				<name>default</name>
			</travellertype>
		</travellertypes>
		<userclasses>																<!-- optional, when absent a single user class is created with a single mode and traveller type (they both also have to be absent) -->
			<userclass id="1" moderef="1" travellertyperef="1">						<!-- travellertyperef optional when no travellertypes are explicitly defined -->
				<name>regular car user</name>
			</userclass>
		</userclasses>
		<timeperiods>																
			<timeperiod id="1">
				<name>Afternoon 2PM-4PM</name>									<!-- description of the period -->
				<starttime>14:00:00</starttime>										<!-- start time without a date in 24h format -->
				<duration>7200</duration>											<!-- duration in seconds -->
			</timeperiod>
		</timeperiods>
	</configuration>
	<oddemands>																		<!-- different formats supported -->
		<odmatrix timeperiodref="1" userclassref="1">								<!-- odmatrix is a potentially square matrix with all origin zones and destination zones, so id references not needed (but optionally available)-->
			<o ref="1">																<!-- in case some elements are not present, it is assumed they are zero, i.e., it can cater for sparse matrices as well -->
				<d ref="1">0.0</d>													<!-- all values are of type double -->
				<d ref="2">150.0</d> 
			</o>
			<o ref="2">
				<d ref="1">300</d>
				<!-- second element absent, sparse matrix to save space, in case of a sparse matrix, all elements must have references -->
			</o>
		</odmatrix>
		<odrowmatrix timeperiodref="1" userclassref="1" ds=",">					<!-- odrowmatrix is a matrix where each origin zone provides a comma separated list of destination values (no exception) -->
			<odrow ref="1">0.0,150.0</odrow>									<!-- origin reference is optional, if not all origins are present, it is assumed the row has no demand at all, destination separator when absent is assumed to be a "," -->																				
			<odrow ref="2">300.0,0.0</odrow>
		</odrowmatrix>
		<odrawmatrix timeperiodref="1" userclassref="1">							<!-- odrawmatrix is a square matrix where all od combinations are provided as one long comma separated list and since the matrix is square the parser delineates the data into the correct od demands -->
			<values os=" " ds=",">0.0,150.0 300.0,0.0</values>
		</odrawmatrix>
	</oddemands>
</macroscopicdemand>

=== TrafficPLANit/PLANitIO/src/test/resources/examples/input/MinimumExample/minimumDemandInput.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<macroscopicdemand
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"								
	 xsi:noNamespaceSchemaLocation="../schema/macroscopicdemandinput.xsd">					
	<configuration>																					
		<timeperiods>																
			<timeperiod id="1">
				<duration>3600</duration>											<!-- duration in seconds -->
			</timeperiod>
		</timeperiods>
	</configuration>
	<oddemands>																		
		<odmatrix timeperiodref="1">
			<o ref="1">																
				<d ref="1">0.0</d>													
				<d ref="2">150.0</d> 
			</o>
			<o ref="2">
				<d ref="1">300</d>
			</o>
		</odmatrix>
	</oddemands>
</macroscopicdemand>

=== TrafficPLANit/PLANitIO/src/test/resources/route_choice/xml/test42/demands.xml
<?xml version="1.0" encoding="UTF-8"?>
<macroscopicdemand xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                        xsi:noNamespaceSchemaLocation="../../../../../main/resources/schema/macroscopicdemandinput.xsd">
      
   <configuration>
	    <userclasses>
	    	<userclass id="1" moderef="1">
	    		<name>1</name>
	    	</userclass>
	    </userclasses>
	    <timeperiods>
	    	<timeperiod id="1">
	    		<name>1</name>
	    		<starttime>00:00:01</starttime>
	    		<duration>43200</duration>
	    	</timeperiod>
	    	<timeperiod id="2">
	    		<name>2</name>
	    		<starttime>12:00:01</starttime>
	    		<duration>43200</duration>
	    	</timeperiod>
	    </timeperiods> 
   </configuration>
       
	<oddemands>
		<odrowmatrix timeperiodref="1" userclassref="1">
			<odrow ref="1">100,200,300,400</odrow>
			<odrow ref="2">200,400,600,800</odrow>
			<odrow ref="3">300,600,900,1200</odrow>
			<odrow ref="4">400,800,1200,1600</odrow>
		</odrowmatrix>
		<odrowmatrix timeperiodref="2" userclassref="1">
			<odrow ref="1">100,200,300,400</odrow>
			<odrow ref="2">200,400,600,800</odrow>
			<odrow ref="3">300,600,900,1200</odrow>
			<odrow ref="4">400,800,1200,1600</odrow>
		</odrowmatrix>
	</oddemands>
</macroscopicdemand>
