=== TrafficPLANit/PLANitIO/src/test/resources/output/linkmetadata.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!--  definition of simple types -->
	<xs:simpleType name="versiontype">
	  <xs:restriction base="xs:string">
	    <xs:pattern value="[0-9]\.[0-9]\.[0-9]"/>
	  </xs:restriction>
	</xs:simpleType>	
	<xs:simpleType name="csvfile">
	  <xs:restriction base="xs:string">
	    <xs:pattern value=".*\.csv"/>
	  </xs:restriction>
	</xs:simpleType>	
	<xs:simpleType name="datatypedescription"> 
    	<xs:restriction base="xs:string"> 
			<xs:enumeration value="double"/>
        	<xs:enumeration value="float"/>
        	<xs:enumeration value="integer"/>
        	<xs:enumeration value="boolean"/> 
      	</xs:restriction> 
	</xs:simpleType> 

	<!-- definition of simple elements -->
	<xs:element name="assignment" type="xs:string"/>
	<xs:element name="csvdata" type="csvfile"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="id" type="xs:positiveInteger"/>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="nr" type="xs:positiveInteger"/>
	<xs:element name="physicalcost" type="xs:string"/>
	<xs:element name="type" type="datatypedescription"/>
	<xs:element name="timestamp" type="xs:dateTime"/>
	<xs:element name="unit" type="xs:string"/>
	<xs:element name="version" type="versiontype"/>
	<xs:element name="virtualcost" type="xs:string"/>
	<xs:element name="price" type="xs:decimal"/>
	
	<!-- Root element -->
	<xs:element name="metadata">
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element ref="timestamp"/>
  				<xs:element ref="version"/>
  				<xs:element ref="description"/>
  				<xs:element ref="configuration"/>
  				<xs:element ref="simulation"/>
  				<xs:element ref="columns"/>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
	<xs:element name="configuration">
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element ref="assignment"/>
  				<xs:element ref="physicalcost"/>
  				<xs:element ref="virtualcost"/>
  				<xs:element ref="timeperiod"/>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
	<xs:element name="timeperiod">
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element ref="id"/>
  				<xs:element ref="name"/>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
	<xs:element name="simulation">
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element ref="iteration"/>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
	<xs:element name="iteration">
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element ref="nr"/>
  				<xs:element ref="csvdata"/>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
	<xs:element name="columns">
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element ref="column" maxOccurs="unbounded"/>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
  	
	<xs:element name="column">
  		<xs:complexType>
  			<xs:sequence>
  				<xs:element ref="name"/>
  				<xs:element ref="unit"/>
  				<xs:element ref="type"/>
  			</xs:sequence>
  		</xs:complexType>
  	</xs:element>
</xs:schema>

=== TrafficPLANit/PLANitIO/src/test/resources/output/linkmetadata.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- 	Tabular output with some meta information, so use a dedicated format for this driven by a schema -->
<!-- 	we choose not to adopt the existing tabular w3 schema approach (http://www.w3.org/TR/tabular-metadata/) which also works with csv because their scheme is defined in json 
		and it does not cater for structured meta data unrelated to the columns apart from a general description (it seems) -->
<metadata
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="linkmetadata.xsd">
	<timestamp>2019-02-05T11:38:24</timestamp>
	<version>0.0.1</version>	
	<description>description of this particular link output</description>
	<outputconfiguration>
		<assignment>traditional static assignment</assignment>
		<physicalcost>BPR</physicalcost>
		<virtualcost>fixed</virtualcost>
		<timeperiod>
			<id>1</id>
			<name>morning peak 6-9</name>			
		</timeperiod>
	</outputconfiguration>
	<simulation>
		<iteration>
			<nr>1</nr>
			<csvdata>linkdata_i1.csv</csvdata>
		</iteration>
	</simulation>
	<columns>
		<column>
			<name>link id</name>
			<unit>none</unit>
			<type>integer</type>				
		</column>
		<column>
			<name>mode id</name>
			<unit>none</unit>
			<type>integer</type>				
		</column>
		<column>
			<name>speed</name>
			<unit>km/h</unit>
			<type>float</type>				
		</column>
		<column>
			<name>density</name>
			<unit>veh/km</unit>
			<type>float</type>				
		</column>
		<column>
			<name>flow</name>
			<unit>veh/h</unit>
			<type>float</type>				
		</column>	
		<column>
			<name>travel time</name>
			<unit>s</unit>
			<type>float</type>				
		</column>								
	</columns>	
</metadata>
